{
 "title": "Hashicorp Vault Non-Prod",
 "description": "Hashicorp Vault Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "${VAR_INTERVAL}" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Cluster Health",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "vault_autopilot_healthy" }
   ]
  },
  {
   "title": "Cluster Health per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "vault_autopilot_node_healthy" }
   ]
  },
  {
   "title": "Failure Tolerance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance"
    }
   ]
  },
  {
   "title": "vault-nonprod DR Status",
   "type": "stat",
   "description": "Status of cluster in DR, Primary, Secondary or undefined",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Last DR and remote DR WAL indexes from both clusters over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "vault-nonprod DR WAL INDEX"
    },
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "vault-nonprod-dr  DR WAL INDEX"
    }
   ]
  },
  {
   "title": "vault-nonprod-dr DR Status",
   "type": "stat",
   "description": "Status of cluster in DR, Primary, Secondary or undefined",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "vault-nonprod DR WAL INDEX",
   "type": "stat",
   "description": "Either the last DR WAL index of the primary or the last index from the primary the secondary cluster wrote. Metric only collected on vault-nonprod cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "vault-nonprod DR WAL INDEX"
    }
   ]
  },
  {
   "title": "vault-nonprod-dr DR WAL INDEX",
   "type": "stat",
   "description": "Either the last DR WAL index of the primary or the last index from the primary the secondary cluster wrote. Metric only collected on ${datasource} cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_replication_wal_last_dr_wal unless vault_replication_fsm_last_remote_wal or vault_replication_fsm_last_remote_wal",
     "legendFormat": "vault-nonprod-dr DR WAL INDEX"
    }
   ]
  },
  {
   "title": "vault-nonprod WAL INDEX",
   "type": "stat",
   "description": "The last WAL index of the primary cluster. Metric only collected on vault-nonprod cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_replication_wal_last_wal", "legendFormat": "vault-nonprod WAL INDEX" }
   ]
  },
  {
   "title": "vault-nonprod-dr WAL INDEX",
   "type": "stat",
   "description": "The last WAL index written. Metric only collected on vault-nonprod-dr cluster nodes.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_replication_wal_last_wal", "legendFormat": "vault-nonprod-dr WAL INDEX" }
   ]
  },
  {
   "title": "License Expiration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "time:YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_core_license_expiration_time_epoch)*1000"
    }
   ]
  },
  {
   "title": "Average Login Time",
   "type": "stat",
   "description": "Average time to login (ms)",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_sum[$interval]) / rate(vault_core_handle_login_request_count[$interval]))"
    }
   ]
  },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[$interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Requests (req/s)",
   "type": "graph",
   "description": "Average core and log request handlers",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "rate(vault_audit_log_request_sum[$__interval])/rate(vault_audit_log_request_count[$__interval])",
     "legendFormat": "Audit Request"
    },
    {
     "expr": "rate(vault_audit_log_response_sum[$__interval])/rate(vault_audit_log_response_count[$__interval])",
     "legendFormat": "Audit Response"
    },
    {
     "expr": "rate(vault_core_handle_request_sum[$__interval])/rate(vault_core_handle_request_count[$__interval])",
     "legendFormat": "Handled by Vault Core"
    }
   ]
  },
  {
   "title": "License Expiration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "time:YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_core_license_expiration_time_epoch)*1000"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "description": "Number of Leases across namespaces",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "description": "Rate of Authentication Requests",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_count[$interval]))"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[$interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "KV Engines",
   "type": "stat",
   "description": "Number of KV Engines across namespaces",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vault_secret_kv_count)" }
   ]
  },
  {
   "title": "Identity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entities",
     "type": "stat",
     "description": "Number of Entities across namespaces",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_identity_num_entities)"
      }
     ]
    },
    {
     "title": "Entity Aliases",
     "type": "stat",
     "description": "Number of Entity Aliases across namespaces",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_identity_entity_alias_count)"
      }
     ]
    },
    {
     "title": "Entity Count by Namespace",
     "type": "table",
     "description": "Entity Count by Namespace",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by (namespace) (vault_identity_entity_count)"
      }
     ]
    },
    {
     "title": "Entity Aliases by Method",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg without(instance) (vault_identity_entity_alias_count)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Tokens",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(vault_token_count)" }
     ]
    },
    {
     "title": "Pending Tokens",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_create_count - vault_token_store_count)"
      }
     ]
    },
    {
     "title": "Tokens by TTL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_ttl)",
       "legendFormat": "{{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Tokens by Namespace",
     "type": "table",
     "description": "Token Count by Namespace",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum without(instance) (vault_token_count)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Token Lookups",
     "type": "timeseries",
     "description": "Token Lookup Rate",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(vault_token_lookup_count[$interval])",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Tokens by Policy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_policy)",
       "legendFormat": "{{ policy }}"
      }
     ]
    },
    {
     "title": "Tokens by Auth Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_auth)",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Set",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault and Raft Leadership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vault Leadership Lost Count",
     "type": "stat",
     "description": "Any count greater than zero means that Vault experienced a leadership change.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_lost_count"
      }
     ]
    },
    {
     "title": "Current Leader",
     "type": "stat",
     "description": "Last reported Vault and Raft leader node",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_raft_state_leader", "legendFormat": "{{ host }}" }
     ]
    },
    {
     "title": "Vault Raft Leader Elections",
     "type": "stat",
     "description": "Increments whenever raft server starts an election. If there are frequent elections or leadership changes, it would likely indicate network issues between the raft nodes, or that the raft servers themselves are unable to keep up with the load.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_state_candidate)"
      }
     ]
    },
    {
     "title": "Raft Leader Last Contact (ms)",
     "type": "timeseries",
     "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_leader_lastContact_sum[$interval]) / rate(vault_raft_leader_lastContact_count[$interval]))"
      }
     ]
    },
    {
     "title": "Vault Leadership Setup Failures",
     "type": "stat",
     "description": "Number of Vault cluster leadership setup failures. Failures indicate bad overall cluster leadership status.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "vault_core_leadership_setup_failed"
      }
     ]
    },
    {
     "title": "Raft Follower State Entered Count",
     "type": "bargauge",
     "description": "Number of times node has entered the follower mode. This happens when a new node joins the cluster or after the end of a leader election.",
     "gridPos": { "h": 3, "w": 8, "x": 4, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "vault_raft_state_follower", "legendFormat": "{{ host }}" }
     ]
    }
   ]
  },
  {
   "title": "Raft Integrated Storage Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Performance (ms)",
     "type": "timeseries",
     "description": "Performance of Raft Integrated Storage Backend",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_storage_delete_sum[$interval]) / rate(vault_raft_storage_delete_count[$interval]))",
       "legendFormat": "AVG DEL"
      },
      {
       "expr": "sum(rate(vault_raft_storage_list_sum[$interval]) / rate(vault_raft_storage_list_count[$interval]))",
       "legendFormat": "AVG LIST"
      },
      {
       "expr": "sum(rate(vault_raft_storage_get_sum[$interval]) / rate(vault_raft_storage_get_count[$interval]))",
       "legendFormat": "AVG GET"
      },
      {
       "expr": "sum(rate(vault_raft_storage_put_sum[$interval]) / rate(vault_raft_storage_put_count[$interval]))",
       "legendFormat": "AVG PUT"
      }
     ]
    },
    {
     "title": "Time Spent (ms)",
     "type": "bargauge",
     "description": "Sum of time spent to perform actions on the storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(vault_raft_storage_delete_sum)",
       "legendFormat": "DEL"
      },
      {
       "expr": "sum(vault_raft_storage_list_sum)",
       "legendFormat": "LIST"
      },
      {
       "expr": "sum(vault_raft_storage_get_sum)",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(vault_raft_storage_put_sum)",
       "legendFormat": "PUT"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Mem Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{})"
      }
     ]
    }
   ]
  }
 ]
}